# Generated by Django 4.2.7 on 2024-01-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=20, unique=True)),
                ('admin_email', models.EmailField(max_length=254)),
                ('ContactNumber', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('password_confirmation', models.CharField(max_length=20)),
            ],
        ),
    ]
