# Generated by Django 4.2.7 on 2024-02-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmeticAdmin', '0002_subadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subadmin',
            name='subadmin_Number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
