# Generated by Django 4.2.7 on 2024-02-05 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CosmeticAdmin', '0003_alter_subadmin_subadmin_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subadmin',
            name='Administator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CosmeticAdmin.administator'),
        ),
        migrations.AlterField(
            model_name='subadmin',
            name='subadmin_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='subadmin',
            name='subadmin_username',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
