# Generated by Django 4.2.7 on 2024-02-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmeticAdmin', '0004_alter_subadmin_administator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subadmin',
            name='admin_username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subadmin',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
