# Generated by Django 4.2.7 on 2024-02-05 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CosmeticAdmin', '0005_subadmin_admin_username_subadmin_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subadmin',
        ),
    ]
