# Generated by Django 4.2.7 on 2024-02-05 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CosmeticAdmin', '0007_subadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subadmin',
        ),
    ]
