# Generated by Django 4.2.7 on 2024-02-05 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CosmeticAdmin', '0011_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subadmin',
            name='Administator',
        ),
        migrations.DeleteModel(
            name='Administator',
        ),
        migrations.DeleteModel(
            name='Subadmin',
        ),
    ]
