# Generated by Django 4.2.7 on 2024-02-05 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CosmeticAdmin', '0012_remove_subadmin_administator_delete_administator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=20, unique=True)),
                ('admin_email', models.EmailField(max_length=254)),
                ('ContactNumber', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('password_confirmation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subadmin_username', models.CharField(max_length=20, unique=True)),
                ('subadmin_email', models.EmailField(max_length=254)),
                ('subadmin_Number', models.CharField(max_length=10)),
                ('subadmin_password', models.CharField(max_length=255)),
                ('subadmin_password1', models.CharField(max_length=20)),
                ('admin_username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('administator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CosmeticAdmin.administator')),
            ],
        ),
    ]
