# Generated by Django 4.2.7 on 2024-02-07 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CosmeticAdmin', '0014_remove_subadmin_admin_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('Subcategory', models.CharField(max_length=30)),
                ('ProductName', models.CharField(max_length=64)),
                ('ActualPrice', models.CharField(max_length=10)),
                ('offerPrice', models.CharField(blank=True, max_length=10)),
                ('ProductColour', models.CharField(max_length=30)),
                ('StackQuantity', models.IntegerField()),
                ('DeliveryCost', models.CharField(max_length=10)),
                ('ProductDetails', models.TextField()),
                ('ProductInformation', models.TextField()),
                ('HowToUse', models.TextField()),
                ('img1', models.FileField(upload_to='product/')),
                ('img2', models.FileField(upload_to='product/')),
                ('img3', models.FileField(upload_to='product/')),
                ('img4', models.FileField(upload_to='product/')),
                ('img5', models.FileField(upload_to='product/')),
                ('subadmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CosmeticAdmin.subadmin')),
            ],
        ),
    ]
