# Generated by Django 4.2.7 on 2024-01-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(blank=True, max_length=50)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('PhoneNumber', models.CharField(max_length=10)),
                ('CustomerEmail', models.EmailField(max_length=254)),
                ('CustomerPassword', models.CharField(max_length=50)),
                ('ConfirmPassword', models.CharField(max_length=50)),
            ],
        ),
    ]
