# Generated by Django 3.2 on 2024-03-28 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CosmeticAdmin', '0016_alter_product_offerprice'),
        ('cosmetics', '0002_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmetics.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CosmeticAdmin.product')),
            ],
        ),
    ]
