# Generated by Django 3.2 on 2024-03-28 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0003_auto_20240328_1517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
