# Generated by Django 4.2.7 on 2024-03-28 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CosmeticAdmin', '0016_alter_product_offerprice'),
        ('cosmetics', '0004_delete_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmetics.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CosmeticAdmin.product')),
                ('retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CosmeticAdmin.subadmin')),
            ],
        ),
    ]
